/**
 * PDF report generator using jsPDF.
 * Dynamically imported from AuditWizard to keep the main bundle lean.
 */

import type { ScoredWorkflow, OverallReadiness } from "./scoring";
import { TIER_CONFIG } from "./config";

interface Article {
  title: string;
  url: string;
  desc: string;
}

export async function generatePdfReport(
  scored: ScoredWorkflow[],
  overall: OverallReadiness,
  links: Article[]
): Promise<Blob> {
  // Dynamic import keeps jspdf out of the initial bundle
  const { default: jsPDF } = await import("jspdf");

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = 210;
  const margin = 20;
  const contentW = W - margin * 2;
  let y = 20;

  const addPage = () => {
    doc.addPage();
    y = 20;
  };

  const checkPage = (needed: number) => {
    if (y + needed > 275) addPage();
  };

  // -- Header --
  doc.setFillColor(30, 26, 20); // bg-inv
  doc.rect(0, 0, W, 36, "F");
  doc.setTextColor(240, 235, 224); // text-inv
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("AUTOMATION AUDIT REPORT", margin, 16);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(160, 152, 136); // text-inv-dim
  doc.text("Generated by Automation Switch | automationswitch.com", margin, 24);
  doc.text(new Date().toLocaleDateString("en-GB"), margin, 30);
  y = 46;

  // -- Overall stats --
  doc.setTextColor(30, 26, 20);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("OVERALL READINESS", margin, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const stats = [
    `Readiness Score: ${overall.overall_score}/100`,
    `Workflows Assessed: ${overall.total_count}`,
    `Actionable: ${overall.actionable_count}`,
    `Automate Now: ${overall.automate_now}`,
    `Do Not Automate: ${overall.do_not_automate}`,
    `Conditional: ${overall.conditional}`,
  ];
  for (const line of stats) {
    doc.text(line, margin, y);
    y += 5.5;
  }
  y += 6;

  // -- Separator --
  doc.setDrawColor(196, 189, 176); // border
  doc.line(margin, y, W - margin, y);
  y += 10;

  // -- Per-workflow breakdown --
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("PER-WORKFLOW BREAKDOWN", margin, y);
  y += 10;

  for (const w of scored) {
    checkPage(60);
    const { result } = w;
    const cfg = TIER_CONFIG[result.tier];
    const { breakdown } = result;

    // Workflow name
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 26, 20);
    doc.text(`${cfg.icon} ${w.name}`, margin, y);
    y += 6;

    // Tier + score
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 90, 72);
    doc.text(`${result.tier} — ${result.score.toFixed(1)}/100`, margin, y);
    y += 7;

    // Dimension scores
    const dims = [
      `Time Cost: ${w.time_cost}`,
      `Error Rate: ${w.error_rate}`,
      `Dependency Risk: ${w.dependency_risk}`,
      `Data Quality: ${w.data_quality}`,
      `Judgment Required: ${w.judgment_pct}%`,
    ];
    doc.setFontSize(9);
    for (const d of dims) {
      doc.text(`• ${d}`, margin + 4, y);
      y += 4.5;
    }
    y += 3;

    // Score contributions
    const contribs = [
      ["Time cost", (breakdown.time_score * 0.3).toFixed(1)],
      ["Error rate", (breakdown.error_score * 0.25).toFixed(1)],
      ["Rule-based", (breakdown.judgment_inverse * 0.25).toFixed(1)],
      ["Dependency", (breakdown.dependency_score * 0.2).toFixed(1)],
    ];
    doc.setFontSize(8);
    doc.setTextColor(133, 125, 114);
    for (const [label, pts] of contribs) {
      doc.text(`${label}: ${pts} pts`, margin + 4, y);
      y += 4;
    }
    y += 2;

    // Flag
    if (result.flag) {
      doc.setFontSize(9);
      doc.setTextColor(200, 134, 26); // amber
      doc.text(`⚠ ${result.flag}`, margin + 4, y);
      y += 6;
    }

    // Separator
    doc.setDrawColor(196, 189, 176);
    doc.line(margin, y, W - margin, y);
    y += 8;
  }

  // -- Recommended reading --
  checkPage(40);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 26, 20);
  doc.text("RECOMMENDED READING", margin, y);
  y += 10;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  for (const article of links) {
    checkPage(12);
    doc.setTextColor(30, 26, 20);
    doc.setFont("helvetica", "bold");
    doc.text(article.title, margin, y);
    y += 4.5;
    doc.setTextColor(133, 125, 114);
    doc.setFont("helvetica", "normal");
    doc.text(article.url, margin, y);
    y += 4.5;
    doc.text(article.desc, margin, y, { maxWidth: contentW });
    y += 8;
  }

  // -- Footer on every page --
  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(133, 125, 114);
    doc.text(
      "automationswitch.com — Workflow Automation Audit",
      margin,
      290
    );
    doc.text(`Page ${p} of ${pages}`, W - margin - 25, 290);
  }

  return doc.output("blob");
}
