import { defineField, defineType } from 'sanity'

export const article = defineType({
  name: 'article',
  title: 'Article',
  type: 'document',
  groups: [
    { name: 'content', title: 'Content', default: true },
    { name: 'taxonomy', title: 'Taxonomy & Revenue' },
    { name: 'seo', title: 'SEO & Meta' },
    { name: 'richSnippets', title: 'Rich Snippets' },
  ],
  fields: [
    // ── CONTENT ──────────────────────────────────────────────
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'content',
      validation: r => r.required(),
    }),
    defineField({
      name: 'kicker',
      title: 'Kicker',
      type: 'string',
      group: 'content',
      description: 'Short editorial phrase shown above the headline in article cards and on the article page. Sets the angle before the headline. E.g. "The missing layer" or "Why teams fail". No punctuation at end. Max 80 chars.',
      validation: r => r.max(80),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'content',
      options: { source: 'title' },
      validation: r => r.required(),
    }),
    defineField({
      name: 'author',
      title: 'Author',
      type: 'reference',
      group: 'content',
      to: [{ type: 'author' }],
      validation: r => r.required(),
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'reference',
      group: 'content',
      to: [{ type: 'category' }],
      validation: r => r.required(),
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero Image',
      type: 'image',
      group: 'content',
      options: { hotspot: true },
      fields: [
        defineField({
          name: 'alt',
          title: 'Alt Text',
          type: 'string',
          description: 'Describe what is in the image — not the article title. Required for SEO and accessibility.',
          validation: r => r.required(),
        }),
      ],
      validation: r => r.required(),
    }),
    defineField({
      name: 'excerpt',
      title: 'Excerpt',
      type: 'text',
      group: 'content',
      rows: 3,
      description: 'Used as the default meta description. Max 200 characters.',
      validation: r => r.required().max(200),
    }),
    defineField({
      name: 'body',
      title: 'Body',
      type: 'array',
      group: 'content',
      of: [
        { type: 'block' },
        {
          type: 'image',
          options: { hotspot: true },
          fields: [
            defineField({ name: 'alt', title: 'Alt Text', type: 'string', validation: r => r.required() }),
            defineField({ name: 'caption', title: 'Caption', type: 'string' }),
          ],
        },
        { type: 'comparisonTable' },
        { type: 'calloutBox' },
        { type: 'proConList' },
        { type: 'howToSteps' },
        { type: 'codeBlock' },
        { type: 'statHighlight' },
      ],
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published At',
      type: 'datetime',
      group: 'content',
      validation: r => r.required(),
    }),
    defineField({
      name: 'lastModified',
      title: 'Last Modified',
      type: 'datetime',
      group: 'content',
      description: 'Update this whenever making significant content changes. Drives the "Updated" badge and dateModified in Article schema.',
    }),
    defineField({
      name: 'readTime',
      title: 'Read Time (minutes)',
      type: 'number',
      group: 'content',
      description: 'Estimated at ~238 words per minute.',
    }),
    defineField({
      name: 'featured',
      title: 'Featured on Homepage',
      type: 'boolean',
      group: 'content',
      initialValue: false,
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      group: 'content',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
      description: '3–7 keyword-rich tags. Lowercase, specific phrases. Maps to article:tag Open Graph properties.',
    }),

    // ── TAXONOMY & REVENUE ────────────────────────────────────
    defineField({
      name: 'primaryPillar',
      title: 'Primary Pillar',
      type: 'string',
      group: 'taxonomy',
      description: 'The main content pillar this article belongs to. Determines the URL prefix.',
      options: {
        list: [
          { title: 'Workflow Automation', value: 'workflow-automation' },
          { title: 'AI Workflows', value: 'ai-workflows' },
          { title: 'Tool Comparisons', value: 'tool-comparisons' },
          { title: 'Automation Audits', value: 'automation-audits' },
          { title: 'Hyperautomation', value: 'hyperautomation' },
          { title: 'Production Readiness', value: 'production-readiness' },
        ],
        layout: 'radio',
      },
      validation: r => r.required(),
    }),
    defineField({
      name: 'secondaryPillar',
      title: 'Secondary Pillar',
      type: 'string',
      group: 'taxonomy',
      description: 'Optional cross-pillar link. Used for internal linking and related content.',
      options: {
        list: [
          { title: 'Workflow Automation', value: 'workflow-automation' },
          { title: 'AI Workflows', value: 'ai-workflows' },
          { title: 'Tool Comparisons', value: 'tool-comparisons' },
          { title: 'Automation Audits', value: 'automation-audits' },
          { title: 'Hyperautomation', value: 'hyperautomation' },
          { title: 'Production Readiness', value: 'production-readiness' },
        ],
        layout: 'dropdown',
      },
    }),
    defineField({
      name: 'audience',
      title: 'Audience',
      type: 'string',
      group: 'taxonomy',
      description: 'Primary audience this article is written for.',
      options: {
        list: [
          { title: 'Operators', value: 'operators' },
          { title: 'Founders', value: 'founders' },
          { title: 'Platform Teams', value: 'platform-teams' },
          { title: 'Content Teams', value: 'content-teams' },
          { title: 'Agencies', value: 'agencies' },
        ],
        layout: 'dropdown',
      },
      validation: r => r.required(),
    }),
    defineField({
      name: 'primaryCTA',
      title: 'Primary CTA',
      type: 'string',
      group: 'taxonomy',
      description: 'Main conversion goal for this article. E.g. "Book an audit", "Sign up for newsletter", "Try Firecrawl (affiliate)".',
      validation: r => r.required(),
    }),
    defineField({
      name: 'secondaryCTA',
      title: 'Secondary CTA',
      type: 'string',
      group: 'taxonomy',
      description: 'Fallback conversion. E.g. "Download the checklist", "Join the newsletter".',
    }),
    defineField({
      name: 'affiliateOffer',
      title: 'Affiliate Offer',
      type: 'string',
      group: 'taxonomy',
      description: 'Which tool/product affiliate link is embedded, if any. E.g. "Firecrawl", "Vercel", "Supabase".',
    }),
    defineField({
      name: 'leadMagnet',
      title: 'Lead Magnet',
      type: 'string',
      group: 'taxonomy',
      description: 'Which downloadable asset or gated content is offered, if any. E.g. "Workflow audit checklist PDF".',
    }),
    defineField({
      name: 'relatedArticles',
      title: 'Related Articles',
      type: 'array',
      group: 'taxonomy',
      of: [{ type: 'reference', to: [{ type: 'article' }] }],
      description: 'Link to exactly 2 related articles for internal linking.',
      validation: r => r.max(3),
    }),
    defineField({
      name: 'updateCadence',
      title: 'Update Cadence',
      type: 'string',
      group: 'taxonomy',
      description: 'How often this article should be reviewed and refreshed.',
      options: {
        list: [
          { title: 'Monthly', value: 'monthly' },
          { title: 'Quarterly', value: 'quarterly' },
          { title: 'Biannually', value: 'biannually' },
          { title: 'Annually', value: 'annually' },
        ],
        layout: 'dropdown',
      },
    }),

    // ── SEO & META ───────────────────────────────────────────
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'object',
      group: 'seo',
      fields: [
        defineField({
          name: 'metaTitle',
          title: 'Meta Title',
          type: 'string',
          description: '50–60 characters. Overrides the article title in <title> and og:title.',
          validation: r => r.max(60),
        }),
        defineField({
          name: 'metaDescription',
          title: 'Meta Description',
          type: 'text',
          rows: 2,
          description: '150–160 characters. Overrides excerpt for meta description and og:description.',
          validation: r => r.max(160),
        }),
        defineField({
          name: 'canonicalUrl',
          title: 'Canonical URL Override',
          type: 'url',
          description: 'Only set if the canonical URL differs from the default /articles/[slug].',
        }),
        defineField({
          name: 'noIndex',
          title: 'No Index',
          type: 'boolean',
          initialValue: false,
          description: 'Set true to exclude this article from search engine indexing.',
        }),
      ],
    }),

    // ── RICH SNIPPETS ────────────────────────────────────────
    defineField({
      name: 'keyTakeaways',
      title: 'Key Takeaways',
      type: 'array',
      group: 'richSnippets',
      of: [{ type: 'string' }],
      description: '3–5 complete sentences. Renders as the TL;DR box at the top of the article. Primary target for Google featured snippets.',
      validation: r => r.max(5),
    }),
    defineField({
      name: 'faq',
      title: 'FAQ',
      type: 'array',
      group: 'richSnippets',
      of: [
        {
          type: 'object',
          name: 'faqItem',
          title: 'FAQ Item',
          fields: [
            defineField({
              name: 'question',
              title: 'Question',
              type: 'string',
              description: 'Phrase as a real user search query (How do I…, Why does…, What is…)',
              validation: r => r.required(),
            }),
            defineField({
              name: 'answer',
              title: 'Answer',
              type: 'text',
              rows: 3,
              description: '2–4 sentences. This text is used verbatim in the FAQPage JSON-LD schema.',
              validation: r => r.required(),
            }),
          ],
          preview: {
            select: { title: 'question' },
          },
        },
      ],
      description: 'Generates FAQPage JSON-LD — expands your Google listing with accordion Q&As. 2–4 items recommended.',
    }),
  ],
  orderings: [
    { title: 'Published Date, New', name: 'publishedAtDesc', by: [{ field: 'publishedAt', direction: 'desc' }] },
    { title: 'Published Date, Old', name: 'publishedAtAsc', by: [{ field: 'publishedAt', direction: 'asc' }] },
  ],
  preview: {
    select: {
      title: 'title',
      author: 'author.name',
      category: 'category.title',
      pillar: 'primaryPillar',
      media: 'heroImage',
    },
    prepare({ title, author, category, pillar, media }) {
      const pillarLabels: Record<string, string> = {
        'workflow-automation': 'Workflow',
        'ai-workflows': 'AI Workflows',
        'tool-comparisons': 'Tools',
        'automation-audits': 'Audits',
        'hyperautomation': 'Hyperauto',
        'production-readiness': 'Prod Ready',
      }
      const pillarLabel = pillar ? pillarLabels[pillar] ?? pillar : 'No pillar'
      return {
        title,
        subtitle: `${pillarLabel} · ${category ?? 'Uncategorised'} · ${author ?? 'No author'}`,
        media,
      }
    },
  },
})
